rails:
  input:
    flows:
      - input_moderation
      - jailbreak_detection

  output:
    flows:
      - output_moderation
      - llm_moderation
      - pii_detection

  retrieval:
    flows:
      - llm_moderation
